-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 509NTGYL8927",
  mode = "3840x2160@60.00",
  position = "-1920x-2160",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 509NTWGL8793",
  mode = "3840x2160@60.00",
  position = "-5760x-2160",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:BOE NE135A1M-NY1",
  disabled = true,
})
